=== noelhorvath/vibrant-abyss-builder/src/schemas/palette.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Pitch Black Palette",
  "type": "object",
  "additionalProperties": false,
  "minProperties": 71,
  "definitions": {
    "hexColor": {
      "$ref": "./definitions.schema.json#/definitions/hexColor"
    },
    "hexOpacity": {
      "$ref": "./definitions.schema.json#/definitions/hexOpacity"
    }
  },
  "properties": {
    "$schema": {
      "type": "string",
      "description": "URI or path to the JSON schema file"
    },
    "background_primary": { "$ref": "#/definitions/hexColor" },
    "background_transparent": { "$ref": "#/definitions/hexColor" },
    "background_drop": { "$ref": "#/definitions/hexColor" },
    "background_selection": { "$ref": "#/definitions/hexColor" },
    "background_selection_highlight": { "$ref": "#/definitions/hexColor" },
    "background_selection_match": { "$ref": "#/definitions/hexColor" },
    "background_selection_player_opacity": {
      "$ref": "#/definitions/hexOpacity"
    },
    "background_surface": { "$ref": "#/definitions/hexColor" },
    "background_surface_active": { "$ref": "#/definitions/hexColor" },
    "background_surface_hover": { "$ref": "#/definitions/hexColor" },
    "foreground_as_background_opacity": { "$ref": "#/definitions/hexOpacity" },
    "foreground_primary": { "$ref": "#/definitions/hexColor" },
    "foreground_secondary": { "$ref": "#/definitions/hexColor" },
    "foreground_dim": { "$ref": "#/definitions/hexColor" },
    "foreground_disabled": { "$ref": "#/definitions/hexColor" },
    "border_dim": { "$ref": "#/definitions/hexColor" },
    "border_focus": { "$ref": "#/definitions/hexColor" },
    "state_error": { "$ref": "#/definitions/hexColor" },
    "state_warning": { "$ref": "#/definitions/hexColor" },
    "state_info": { "$ref": "#/definitions/hexColor" },
    "state_success": { "$ref": "#/definitions/hexColor" },
    "state_remote": { "$ref": "#/definitions/hexColor" },
    "state_debug": { "$ref": "#/definitions/hexColor" },
    "git_added": { "$ref": "#/definitions/hexColor" },
    "git_conflict": { "$ref": "#/definitions/hexColor" },
    "git_deleted": { "$ref": "#/definitions/hexColor" },
    "git_modified": { "$ref": "#/definitions/hexColor" },
    "git_ignored": { "$ref": "#/definitions/hexColor" },
    "git_renamed": { "$ref": "#/definitions/hexColor" },
    "git_submodule": { "$ref": "#/definitions/hexColor" },
    "git_untracked": { "$ref": "#/definitions/hexColor" },
    "git_word_added": { "$ref": "#/definitions/hexColor" },
    "git_word_deleted": { "$ref": "#/definitions/hexColor" },
    "syntax_attribute": { "$ref": "#/definitions/hexColor" },
    "syntax_character": { "$ref": "#/definitions/hexColor" },
    "syntax_comment": { "$ref": "#/definitions/hexColor" },
    "syntax_comment_documentation": { "$ref": "#/definitions/hexColor" },
    "syntax_constant": { "$ref": "#/definitions/hexColor" },
    "syntax_control": { "$ref": "#/definitions/hexColor" },
    "syntax_css": { "$ref": "#/definitions/hexColor" },
    "syntax_enum_member": { "$ref": "#/definitions/hexColor" },
    "syntax_function": { "$ref": "#/definitions/hexColor" },
    "syntax_json_key": { "$ref": "#/definitions/hexColor" },
    "syntax_keyword": { "$ref": "#/definitions/hexColor" },
    "syntax_method": { "$ref": "#/definitions/hexColor" },
    "syntax_numeric": { "$ref": "#/definitions/hexColor" },
    "syntax_operator": { "$ref": "#/definitions/hexColor" },
    "syntax_operator_special": { "$ref": "#/definitions/hexColor" },
    "syntax_regex": { "$ref": "#/definitions/hexColor" },
    "syntax_regex_character": { "$ref": "#/definitions/hexColor" },
    "syntax_regex_operator": { "$ref": "#/definitions/hexColor" },
    "syntax_regex_punctuation": { "$ref": "#/definitions/hexColor" },
    "syntax_static": { "$ref": "#/definitions/hexColor" },
    "syntax_string": { "$ref": "#/definitions/hexColor" },
    "syntax_type": { "$ref": "#/definitions/hexColor" },
    "syntax_variable": { "$ref": "#/definitions/hexColor" },
    "syntax_variable_constant": { "$ref": "#/definitions/hexColor" },
    "ansi_black": { "$ref": "#/definitions/hexColor" },
    "ansi_red": { "$ref": "#/definitions/hexColor" },
    "ansi_green": { "$ref": "#/definitions/hexColor" },
    "ansi_yellow": { "$ref": "#/definitions/hexColor" },
    "ansi_blue": { "$ref": "#/definitions/hexColor" },
    "ansi_magenta": { "$ref": "#/definitions/hexColor" },
    "ansi_cyan": { "$ref": "#/definitions/hexColor" },
    "ansi_white": { "$ref": "#/definitions/hexColor" },
    "ansi_bright_black": { "$ref": "#/definitions/hexColor" },
    "ansi_bright_red": { "$ref": "#/definitions/hexColor" },
    "ansi_bright_green": { "$ref": "#/definitions/hexColor" },
    "ansi_bright_yellow": { "$ref": "#/definitions/hexColor" },
    "ansi_bright_blue": { "$ref": "#/definitions/hexColor" },
    "ansi_bright_magenta": { "$ref": "#/definitions/hexColor" },
    "ansi_bright_cyan": { "$ref": "#/definitions/hexColor" },
    "ansi_bright_white": { "$ref": "#/definitions/hexColor" }
  }
}

=== noelhorvath/vibrant-abyss-builder/src/palette.json
{
  "$schema": "schemas/palette.schema.json",
  "background_primary": "#000000",
  "background_transparent": "#00000000",
  "background_drop": "#0e0e0e",
  "background_selection_player_opacity": "3d",
  "background_selection": "#34a7ff70",
  "background_selection_match": "#ffee0030",
  "background_selection_highlight": "#ffee0050",
  "background_surface": "#1e1e1e",
  "background_surface_hover": "#2e2e2e",
  "background_surface_active": "#3e3e3e",
  "foreground_as_background_opacity": "20",
  "foreground_primary": "#dedede",
  "foreground_secondary": "#cdcdcd",
  "foreground_dim": "#9c9c9c",
  "foreground_disabled": "#4e4e4e",
  "border_dim": "#1e1e1e",
  "border_focus": "#ffee00",
  "state_error": "#ff6439",
  "state_warning": "#e7d427",
  "state_info": "#34a7ff",
  "state_success": "#26e019",
  "state_remote": "#12c083",
  "state_debug": "#4d11c2",
  "git_added": "#94eba4",
  "git_conflict": "#ff6439",
  "git_deleted": "#ff6439",
  "git_modified": "#ffb74a",
  "git_ignored": "#9c9c9c",
  "git_renamed": "#bd93f9",
  "git_submodule": "#9cdcfe",
  "git_untracked": "#5fd789",
  "git_word_added": "#94eba450",
  "git_word_deleted": "#ff643950",
  "syntax_attribute": "#9cdcfe",
  "syntax_character": "#f1d495",
  "syntax_comment": "#94d378",
  "syntax_comment_documentation": "#66baff",
  "syntax_constant": "#5ec7ff",
  "syntax_control": "#34a7ff",
  "syntax_css": "#f1d495",
  "syntax_enum_member": "#16dcff",
  "syntax_function": "#e6e6b1",
  "syntax_keyword": "#4ec1fb",
  "syntax_numeric": "#aedf8d",
  "syntax_operator": "#dedede",
  "syntax_operator_special": "#fe77ef",
  "syntax_regex": "#ffb74a",
  "syntax_regex_character": "#ff8566",
  "syntax_regex_operator": "#e6e6b1",
  "syntax_regex_punctuation": "#daa18a",
  "syntax_static": "#fe77ef",
  "syntax_string": "#eaab93",
  "syntax_type": "#20deb8",
  "syntax_variable": "#abe2ff",
  "syntax_variable_constant": "#0df8fc",
  "ansi_black": "#1a1a1a",
  "ansi_bright_black": "#666666",
  "ansi_red": "#ff6439",
  "ansi_bright_red": "#ff8566",
  "ansi_green": "#26e019",
  "ansi_bright_green": "#5fd789",
  "ansi_yellow": "#e7d427",
  "ansi_bright_yellow": "#ffee00",
  "ansi_blue": "#34a7ff",
  "ansi_bright_blue": "#5ec7ff",
  "ansi_magenta": "#d129c2",
  "ansi_bright_magenta": "#fe77ef",
  "ansi_cyan": "#0bdee3",
  "ansi_bright_cyan": "#0df8fc",
  "ansi_white": "#dedede",
  "ansi_bright_white": "#ffffff"
}
